import openai
import os
from googleapiclient.errors import HttpError

# You will need to set your OpenAI API key
openai.api_key = os.getenv("OPENAI_API_KEY")

def generate_reply(email_context):
    """
    Function to generate an auto-reply using GPT-3 based on the context of an email chain.
    :param email_context: str, The context of the email chain.
    :return: str, The draft reply generated by the GPT-3 model.
    """
    try:
        # Use the OpenAI API to generate a response
        response = openai.Completion.create(
            engine="text-davinci-002",
            prompt=email_context,
            temperature=0.5,
            max_tokens=150
        )

        # Extract the generated message from the response
        message = response.choices[0].text.strip()

        return message

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

def save_draft(service, user_id, message_body):
    """
    Create and save a draft email.
    :param service: Authorized Gmail API service instance.
    :param user_id: User's email. The special value "me" can be used to indicate the authenticated user.
    :param message_body: The body of the email message, including headers.
    :return: Draft object, including draft ID and message meta data.
    """
    try:
        message = {'raw': message_body}
        draft = service.users().drafts().create(userId=user_id, body=message).execute()

        print(f"Draft id: {draft['id']}")
        print(f"Draft message: {draft['message']}")

        return draft

    except HttpError as error:
        print(f"An error occurred: {error}")
        return None